In [4]:
import pandas as pd 
import sqlite3

In [6]:
sales = pd.read_csv('data/sales_clean.csv', parse_dates=['InvoiceDate'])

In [7]:
conn = sqlite3.connect('data/retail.db')
sales.to_sql('sales', conn, index=False, if_exists='replace')

1007910

In [8]:
query = "SELECT * FROM sales LIMIT 5"
pd.read_sql(query, conn)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [9]:
query = "SELECT SUM(Revenue) FROM sales"
pd.read_sql(query,conn)

   SUM(Revenue)
0  2.021955e+07

In [10]:
sales['Revenue'].sum()

np.float64(20219545.188)

In [16]:
query = """
SELECT Country, SUM(revenue) AS Revenue
FROM sales
WHERE Country != 'United Kingdom'
GROUP BY Country 
ORDER BY Revenue DESC
LIMIT 10
"""
pd.read_sql(query,conn)

       Country     Revenue
0         EIRE  658767.310
1  Netherlands  554038.090
2      Germany  425019.711
3       France  350456.090
4    Australia  169283.460
5        Spain  108332.490
6  Switzerland  100685.590
7       Sweden   91869.820
8      Denmark   68580.690
9      Belgium   65387.820

In [24]:
query = """
SELECT Country, SUM(Revenue) AS Revenue, 
COUNT(DISTINCT "Customer ID") AS TotalCustomers
FROM sales
WHERE Country != 'United Kingdom'
GROUP BY Country 
ORDER BY Revenue DESC
LIMIT 10 
"""
pd.read_sql(query,conn)

       Country     Revenue  TotalCustomers
0         EIRE  658767.310               5
1  Netherlands  554038.090              22
2      Germany  425019.711             107
3       France  350456.090              95
4    Australia  169283.460              15
5        Spain  108332.490              41
6  Switzerland  100685.590              22
7       Sweden   91869.820              19
8      Denmark   68580.690              12
9      Belgium   65387.820              29

In [25]:
query = """
SELECT StockCode,SUM(Revenue)as Revenue
FROM sales
WHERE StockCode GLOB '[0-9]*'
GROUP BY StockCode
ORDER BY Revenue DESC
LIMIT 10 
"""
pd.read_sql(query,conn)

  StockCode    Revenue
0     22423  330590.32
1    85123A  261168.73
2    85099B  182680.98
3     47566  148318.28
4     84879  129324.49
5     22086  117760.29
6     79321   80540.88
7     22197   79520.20
8     22386   76324.62
9     84347   71300.40

In [26]:
query= """
SELECT strftime ('%Y-%m', InvoiceDate) AS Month,
SUM(Revenue)AS Revenue
FROM sales 
WHERE InvoiceDate < '2011-12-01'
GROUP BY Month 
ORDER BY Revenue DESC
"""
pd.read_sql(query,conn)

      Month      Revenue
0   2011-11  1503866.780
1   2010-11  1464293.142
2   2010-10  1161902.220
3   2011-10  1151263.730
4   2011-09  1056435.192
5   2010-09   921696.991
6   2010-03   830915.261
7   2009-12   822483.950
8   2010-12   821452.730
9   2011-05   769296.610
10  2011-06   760547.010
11  2010-06   749537.310
12  2011-08   746779.320
13  2011-07   718076.121
14  2011-03   716215.260
15  2010-08   695251.910
16  2010-04   678875.252
17  2010-05   657705.500
18  2010-01   651155.112
19  2010-07   648810.270
20  2011-01   612628.010
21  2010-02   551504.726
22  2011-04   536968.491
23  2011-02   522545.560